# Generated by Django 5.0.2 on 2024-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='youssef@gmail.com', max_length=254, unique=True),
        ),
    ]
