# Generated by Django 5.0.2 on 2024-02-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stream', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload_image/')),
            ],
        ),
    ]
