# Generated by Django 5.0.2 on 2024-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stream', '0006_remove_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='upload_image/'),
        ),
    ]
