# Generated by Django 5.0.2 on 2024-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stream', '0007_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.FileField(upload_to='upload_image/'),
        ),
    ]
