# Generated by Django 5.0.2 on 2024-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stream', '0008_alter_media_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.CharField(max_length=100)),
                ('Video', models.FileField(upload_to='upload_video/')),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='upload_image/'),
        ),
    ]
